# Site settings
title: Hari Om Gaur
email: hogaur@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    IIT Jodhpur alumnus,
    coder by profession,
    musician-writer at heart. I write about my experieces with life, code and musical notes.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hogaur.github.io" # the base hostname & protocol for your site
twitter_username: hogaur
github_username:  hogaur

# Build settings
markdown: kramdown
