title: Hari Om Gaur
author: hogaur
email: hogaur@gmail.com
tagline: A blog dedicated to tech and personality. Only if I automated all that goes in my head...
description: >-
  My journey, learnings & experiences about software engineering, life & music.
url: "hariomgaur.in"
baseurl: ""
theme: minima
show_excerpts: true

twitter_username: hogaur
linkedin_username: hogaur
github_username:  hogaur

google_analytics: 'UA-67482601-1'

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

header_pages:
  - index.markdown
  - about.markdown
  - showcase.markdown
  - posts.markdown
  - poetry.markdown
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
