name: HariOm
tagline: 'Experience joy in the journey'
author:
  name: Hari Om Gaur
  email: hogaur@gmail.com
  github: hogaur
  twitter: hogaur
description: 'Life Music & Code'
meta_description: "Writing about my experiences of the journey."
sections: ['Life', 'Music', 'Code']
aboutPage: true

markdown: redcarpet
highlighter: pygments

paginate: 20
baseurl: /
domain_name: 'http://hariomgaur.in'
google_analytics: 'UA-67482601-1'
disqus: false
disqus_shortname: 'your-disqus-shortname'

# Details for the RSS feed generator
url:            'http://hariomgaur.in'
author:         'Hari Om Gaur'
authorTwitter:  '@hogaur'

permalink:       /:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
